# Markdown Linting Configuration
# Reference: https://github.com/igorshubovych/markdownlint-cli

default: true

# Disabled rules
MD013: false  # Line length handled by editor/formatter
MD033: false  # Allow inline HTML for badges, tables
MD060: false  # Flexibility in reference definitions

# List formatting
MD004:
  style: consistent  # Allows * or - (but must be consistent per file)
MD007:
  indent: 2          # 2-space indentation for nested lists
MD029:
  style: one         # Use 1. for all ordered list items

# Whitespace handling
MD009:
  br_spaces: 0                  # No trailing spaces for line breaks
  list_item_empty_lines: false  # No empty lines in list items
  strict: false                 # Allow trailing spaces in code blocks
MD010:
  code_blocks: true             # Check for hard tabs in code blocks
  ignore_code_languages: []     # No languages excluded from tab check

# Document structure
MD025:
  front_matter_title: ""        # Ignore frontmatter title check